// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbeCTyWvdbhrgcvRhjXFEBV6CC8x4_UKw',
    appId: '1:1014733684860:web:062f10c48d7c3cb87809f9',
    messagingSenderId: '1014733684860',
    projectId: 'healnixd',
    authDomain: 'healnixd.firebaseapp.com',
    storageBucket: 'healnixd.firebasestorage.app',
    measurementId: 'G-3L58Z4CFW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATN94OhADwkcTO_0j7sikXYFcFkHf-VCc',
    appId: '1:1014733684860:android:ec116bc97af61dc27809f9',
    messagingSenderId: '1014733684860',
    projectId: 'healnixd',
    storageBucket: 'healnixd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDNODtwG9FUhUAwOFpLg8aH7sUVbqxqU',
    appId: '1:1014733684860:ios:88fae137b1e95ff47809f9',
    messagingSenderId: '1014733684860',
    projectId: 'healnixd',
    storageBucket: 'healnixd.firebasestorage.app',
    iosBundleId: 'com.example.healnixd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWDNODtwG9FUhUAwOFpLg8aH7sUVbqxqU',
    appId: '1:1014733684860:ios:88fae137b1e95ff47809f9',
    messagingSenderId: '1014733684860',
    projectId: 'healnixd',
    storageBucket: 'healnixd.firebasestorage.app',
    iosBundleId: 'com.example.healnixd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbeCTyWvdbhrgcvRhjXFEBV6CC8x4_UKw',
    appId: '1:1014733684860:web:e656f83e520133227809f9',
    messagingSenderId: '1014733684860',
    projectId: 'healnixd',
    authDomain: 'healnixd.firebaseapp.com',
    storageBucket: 'healnixd.firebasestorage.app',
    measurementId: 'G-J5Y4TGSGVY',
  );
}
